### ISSUE TITLE
Wrong disassembler output when there are both DSR prefix and offset

### ISSUE THREAD

**Issue by user202729** [LBPHacker/CasioEmu#18]
`FE9F 9189 0001` should disassembles to `st r1, dsr:1[er8]`, not `st r1, 1dsr:[er8]`.

**Comment by LBPHacker** [comment]
Wooo I forgot to fix this. Does any of your PRs fix this?

**Comment by user202729** [comment]
No, unfortunately. I can't figure out how the write opcodes part works.

**Comment by LBPHacker** [comment]
I'll fix it later today then.
