### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ghost** [LBPHacker/CasioEmu#3]
On my machine, the emulator occupies around 100% of the CPU resources available to it.
Why is that?

**Comment by LBPHacker** [comment]
Is this still relevant? I'll eventually look into it if it is. No idea why it would do that. My only guess right now is that the cycle scheduler jams up and requests more cycles to be emulated in every frame.

Have you tried to compile with -O2? Not a solution by any means, it just occurred to me while looking at the Makefile.

**Comment by LBPHacker** [comment]
@SopaXorzTaker did say the emulator spent most of the time in his graphics driver so I guess #10 fixes this too. Closing for now.
