### ISSUE TITLE
Fetch the ROM file automatically

### ISSUE THREAD

**Issue by ghost** [LBPHacker/CasioEmu#6]
As we can't include the ROM binary here because of the DMCA concerns, I suggest hosting it somewhere else and downloading it after showing the user a license agreement of some sort.

**Comment by LBPHacker** [comment]
That still seems a little shady to me. I don't think we need to automate
this.

2018-01-06 17:43 GMT+01:00 SopaXorzTaker <notifications@github.com>:

**Comment by ghost** [comment]
Well, we could at least inform them that they need a ROM file which "can be obtained from ███████ (████)".

Maybe an offer to specify a direct URL this can be downloaded from?
Also, we could include the SHA256 hash of the ROM to check the downloaded file against.

**Comment by LBPHacker** [comment]
Yeah I like the hash idea, it'd ship with the model data.

And then the emulator would politely tell the user to get a ROM from
*somewhere* if it was missing. I really don't wanna introduce downloading
stuff into the mix though.
